let listMots = [
    // La lettre A (a);
    'amour', 'aimer', 'aller', 'ajouter', 'arrange', 'arranger', 'amener', 'amène', 'ajoute', 'allié', 'aille', 'ailles', 'anal', 'anus', 'ananas', 'abeille', 'algorithme', 'avocat', 'azur', 'aspect', 'acné', 'alumette', 'alluviant', 'avoir', 'ai', 'aie', 'avait', 'avez', 'aviez', 'ameliore', 'ameliorer', 'alain', 'alterer', 'allons', 'allez', 'allions', 'alliez', 'ail', 'ails', 'aile', 'ailes', 'ami', 'amis', 'amicale', 'aimable', 'amicales', 'avions', 'avion', 'aviez', 'avaient', 'amoureux', 'amoureuse', 'à', 'a', 'as', 'atout', 'abel', 'arial', 'arriere', 'avant', 'après', 'armer', 'argot', 'arme', 'aladin', 'after', 'amer', 'aimables', 'alicia', 'arcel', 'alumer', 'alume', 'action', 'actions', 'actionner', 'actionne', 'ayant', 'ait', 'ayez', 'aient', 'allure', 'abus', 'abuse', 'abuser', 'abruiti', 'apat', 'acacia', 'acaju', 'attire', 'attirer', 'attention', 'aboyer',
    // La lettre B(b);
    'banane', 'balle', 'ballon', 'balles', 'ballons', 'balise', 'bague', 'bougie', 'boule', 'bouge', 'bouger', 'bouder', 'boudha', 'boudin', 'bijoux', 'bise', 'bisou', 'belle', 'bon', 'bonne', 'bien', 'bonbon', 'boom', 'bombe', 'bombarder', 'bombardier', 'bombarde', 'boire', 'buvons', 'buvant', 'boivent', 'boive', 'boie', 'bois', 'brousse', 'buvait', 'boiras', 'boira', 'buter', 'boite', 'boiter', 'boiteux', 'boiteuse', 'bientôt', 'biai', 'broyer', 'bord', 'bordur', 'border', 'bordel', 'barre', 'bar', 'barrer', 'bavard', 'bavarder','bifirquer', 'baliverne', 'bouche', 'bas', 'bille', 'bailler', 'balai', 'balayer', 'briser', 'bruce', 'bave', 'baver', 'bavure', 'bras', 'brun', 'brune', 'blonde', 'blond', 'bile', 'biliaire', 'boude', 'boudait', 'bouger', 'bouge', 'bougeons', 'bougez','brique','briquet','borne',
    // La lettre C(c);
    'calme', 'camion', 'calçon', 'calcul', 'calculer', 'cul', 'courage', 'cout', 'coute', 'couter', 'courageux', 'courageuse','carure','carré','couler','cool','coulage','coule','clé','clavier','clavicule','clement','clemence','clause','clot','cause','causer','accuser','accuse','causant','causante','casser','case','cases','creux','creuse','creuser','court','cours','course','courir','courez','courant','crise','croix','choix','croiser','choisir','choisisser','croisson','croisant','croisons','compte','compter','compté','conte','contenir','contient','cité','citer','complet','couple','compassion','compas','compact','courbe','croire','croyant','coran','canaux','canal','canard','canarder','capturer','capture','compus','crompe','courbatures','courbure','claire','clair','caillou','caviare','chef','clef','click','clique','cliquer','croquer','croque','coq','coqueluche','calmer','calmant','colmater','cardiaque','cardio','cargo','cabine','cabinda','chaine','chaise','chasse','cache','cacher','cochon','cochons','coucher','couché','couche','couches','crash','crasher','calamar','calciné','calciner','calcine','calons','couchant','couchons','cinq','Cameroune','caramelle',
// La lettre D('d');
'DAMBA','dame','dam','adam','adel','damer','damier','domage','dormir','doser','dosage','dose','doux','douce','douze','bain','double','david','dissoud','dissoudre','dissous','dissolution','dilution','diabete','diarrhée','davantage','avantage','debout','demarrer','demarre','debrouiller','debrouillard','delire','dedier','didier','diable','dalle','dé','deux','dix','de','des','du','debut','débit','debuter','debutant','débiter','debutons','danse','danser','dense','don','dont','donc','dans','dedans','devant','derrière','dernière','dernier','dictée','dictionaire','dire','dit','dis','disant','disons','disez','disent','disait','digne','dignité','digital','département','départemental','départementaux','décision','décider','décisif','décisive','désolé','décourager','décourageant','dédin','donne','donner','données','donné','donnant','donneur','donateur','domine','dominer','dominant','domination','démoniaque','démonial','démoniaux','doigt','doigts','dormons','dormant','duper','dupe','dupant','dupons','doubler','doublage','doublant','doublons','doublé','diaboliser','dolisie','dalas','daller','dan','damien','doper','drone','drink',
// La lettre E(e) : 
'et','être','été','êtes','dette','étant','est','élan','élancé','erlanmeyer','etang','étanche','ère','en','envoie','environ','environnement','environnant','aux','éliminer','éliminé','élimine','envoyer','envoyé','éviter','évite','échapper','échappe','étirer','étiré','éloigner','éloigné','élève','élèves','élément','charge','chargé','élémentaire','écran','éssaie','éssayer','éssayé','enfoncer','enfouir','enfant','éléphant','élégant','élégance','emmener','emmène','amené','amen','émarger','émargence','émargent','émeraude','émanant','état','états','épaule','estomac','abdo','abdominal','Ernest','Epictète','Epicure','Eratosthenes','éradiquer','empoisonner','empoisonnement','empoisonnable','électron','électeur','élection','élu','emma','emmanuel','emmanuelle','émaner','émane','étourdi','étrangé','étrange','écrit','écrire','écrite','écriture','écritoire','étoile','étoilé','écrivain','Erwin','erreur','époustouflant','épous','épouse','épouser','épousé','émerveillé','étroit','esprit','énumérer','énuméré','énumère','énumérateur','énumératif','elfe','aigle','espagne','éthiopie','épître','eswatinie','estonie','équateur','eye','eu','eux','eue','eus','eues','étés','es','Est','étape','étapes','éternel','éternelle','éternité','éternellement','eurent','émeute','énergie','énerver','énervé','énervant','énergétique','énergique','célérité','célèbre','célébrité','célébré','célébrer','célibataire','célibat','divorcer','divorcé','elle','elles','est-ce que','allant','alors','écume',
// La lettre F(f) : 
'femme','faim','ferme','fermer','fermé','fin','faux','fausse','fausser','faussé','fade','famille','familier','familière','bonjour','bonsoir','bienvenue','dors','dodo','bro','faible','farce','farceur','farceuse','faché','facher','fâcheux','fourmie','fourmilière','four','cacao'

]
/*
for (var i = 0; i < listMots.length; i++) { 
    console.log(listMots[i]);!
} 
*/
console.log(listMots.length);